{*
* 2017 Azelab
*
* NOTICE OF LICENSE
*
* This source file is subject to the Academic Free License (AFL 3.0)
* that is bundled with this package in the file LICENSE.txt.
* It is also available through the world-wide-web at this URL:
* http://opensource.org/licenses/afl-3.0.php
* If you did not receive a copy of the license and are unable to
* obtain it through the world-wide-web, please send an email
* to license@areama.net so we can send you a copy immediately.
*
*
*  @author Azelab <support@azelab.com>
*  @copyright  2017 Azelab
*  @license    http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
*  International Registered Trademark & Property of Azelab
*}
<div class="arcontactus-config-panel {if $active_tab != 'ArContactUsCallbackConfig'}hidden{/if}" id="arcontactus-callback">
    <div class="row">
        <div class="col-sm-9">
            {$form->generateForm($callbackFormParams) nofilter}{* HTML content generated by HelperForm, no escape necessary *}
        </div>
        <div class="col-sm-3">
            <div class="panel">
                <div class="panel-heading">
                    <i class="icon-info"></i> {l s='Onesignal' mod='arcontactus'}
                </div>
                <div class="form-wrapper">
                    <p>
                        {l s='This module can be integrated with Onesignal module. You can buy module by following link:' mod='arcontactus'}
                    </p>
                    <p>
                        <a href="https://addons.prestashop.com/en/emails-notifications/27022-onesignal-browser-push-notifications-cart-reminder.html" target="_blank">https://addons.prestashop.com/en/emails-notifications/27022-onesignal-browser-push-notifications-cart-reminder.html</a>
                    </p>
                    <p>
                        {l s='Using Onesignal integration, this module can send web push notifications about callback request to all subscribed employeers.' mod='arcontactus'}
                    </p>
                    {if $onesignalInstalled}
                        <p style="color: green">
                            {l s='Onesignal module is installed in your shop.' mod='arcontactus'}<br/>
                            {l s='Please subscribe to admin notifications in Onesignal configuration at "Admin messages settings" section.' mod='arcontactus'} <a target="_blank" href="{$onesignalConfigLink|escape:'htmlall':'UTF-8'}">{l s='Go to Onesignal configuration.' mod='arcontactus'}</a>
                        </p>
                    {else}
                        <p style="color: red">
                            {l s='Onesignal module is not installed in your shop.' mod='arcontactus'}
                        </p>
                    {/if}
                </div>
            </div>
            <div class="panel">
                <div class="panel-heading">
                    <i class="icon-info"></i> {l s='Google reCaptcha V3' mod='arcontactus'}
                </div>
                <div class="form-wrapper">
                    <p>
                        {l s='This module can be integrated with Google reCaptcha to prevent bots from sending callback requests.' mod='arcontactus'}
                    </p>
                    <p>
                        {l s='To use this integration you need to get reCaptcha V3 key and secret. Please follow this link:' mod='arcontactus'}
                    </p>
                    <p>
                        <a href="https://g.co/recaptcha/v3 " target="_blank">https://g.co/recaptcha/v3</a>
                    </p>
                </div>
            </div>
            <div class="panel">
                <div class="panel-heading">
                    <i class="icon-info"></i> {l s='Twilio' mod='arcontactus'}
                </div>
                <div class="form-wrapper">
                    <p>
                        {l s='This module can be integrated with Twilio SMS service.' mod='arcontactus'}
                    </p>
                    <p>
                        {l s='To use this integration you need to signup to Twilio. Please follow this link:' mod='arcontactus'}
                    </p>
                    <p>
                        <a href="https://www.twilio.com/try-twilio" target="_blank">https://www.twilio.com/try-twilio</a>
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>