{*
* 2017 Azelab
*
* NOTICE OF LICENSE
*
* This source file is subject to the Academic Free License (AFL 3.0)
* that is bundled with this package in the file LICENSE.txt.
* It is also available through the world-wide-web at this URL:
* http://opensource.org/licenses/afl-3.0.php
* If you did not receive a copy of the license and are unable to
* obtain it through the world-wide-web, please send an email
* to license@areama.net so we can send you a copy immediately.
*
*
*  @author Azelab <support@azelab.com>
*  @copyright  2017 Azelab
*  @license    http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
*  International Registered Trademark & Property of Azelab
*}
<div class="arcontactus-config-panel {if $active_tab != 'ArContactUsLiveChatConfig'}hidden{/if}" id="arcontactus-livechat">
    <div class="row">
        <div class="col-sm-9">
            {$form->generateForm($liveChatFormParams) nofilter}{* HTML content generated by HelperForm, no escape necessary *}
        </div>
        <div class="col-sm-3">
            <div class="panel">
                <div class="panel-heading">
                    <i class="icon-info"></i> {l s='Tawk.to' mod='arcontactus'}
                </div>
                <div class="form-wrapper">
                    <p>
                        {l s='This module can be integrated with Tawk.to live chat. You can sign up Tawk.to following this link:' mod='arcontactus'}
                    </p>
                    <p>
                        <a href="https://www.tawk.to/" target="_blank">https://www.tawk.to/</a>
                    </p>
                </div>
            </div>
                    
            <div class="panel">
                <div class="panel-heading">
                    <i class="icon-info"></i> {l s='Crisp' mod='arcontactus'}
                </div>
                <div class="form-wrapper">
                    <p>
                        {l s='To integrate this module with Crisp, please follow this link:' mod='arcontactus'}
                    </p>
                    <p>
                        <a href="https://goo.gl/ak2TLh" target="_blank">https://app.crisp.chat/initiate/signup/</a>
                    </p>
                </div>
            </div>
                    
            <div class="panel">
                <div class="panel-heading">
                    <i class="icon-info"></i> {l s='Intercom' mod='arcontactus'}
                </div>
                <div class="form-wrapper">
                    <p>
                        {l s='To integrate this module with Intercom, please follow this link:' mod='arcontactus'}
                    </p>
                    <p>
                        <a href="https://www.intercom.com/" target="_blank">https://www.intercom.com/</a>
                    </p>
                </div>
            </div>
                    
            <div class="panel">
                <div class="panel-heading">
                    <i class="icon-info"></i> {l s='Zendesk chat' mod='arcontactus'}
                </div>
                <div class="form-wrapper">
                    <p>
                        {l s='To integrate this module with Zendesk chat (zopim), please follow this link:' mod='arcontactus'}
                    </p>
                    <p>
                        <a href="https://www.zopim.com/" target="_blank">https://www.zopim.com/</a>
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>